import { LegalPageLayout } from "@/components/legal/LegalPageLayout";

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" updated="August 26, 2026">
      <p>
        BetterCallz (&ldquo;BetterCallz&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) is a unit of Chirag Digital Pvt Ltd. These
        Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the BetterCallz website and application
        (the &ldquo;Service&rdquo;). By creating an account or using the Service, you agree to these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        BetterCallz lets you practice cold calls against an AI-simulated prospect and provides AI-generated coaching,
        scoring, and feedback. The Service is a training and practice tool. Outputs from the Service (prospect
        responses, coaching tips, scores, and feedback) are generated by AI and are provided for practice purposes
        only &mdash; they are not professional, legal, or financial advice, and are not guaranteed to be accurate.
      </p>

      <h2>2. Accounts</h2>
      <p>
        You must create an account to use the Service. You&apos;re responsible for keeping your login credentials
        secure and for all activity under your account. You must provide a valid email address you control, since we
        use it for account verification and important notices.
      </p>

      <h2>3. Free trial and credits</h2>
      <p>
        New accounts receive a limited number of free practice calls, each capped at a maximum duration. Once your
        free trial is used, continuing to use the Service requires purchasing a credit pack. Each credit permits one
        practice call, up to the maximum duration in effect at the time of purchase. Credits do not expire unless we
        state otherwise at the time of a future change. See our{" "}
        <a href="/refund" className="underline underline-offset-4">
          Refund Policy
        </a>{" "}
        for details on payments.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose, or to harass, abuse, or impersonate any person.</li>
        <li>
          Attempt to bypass, disable, or interfere with any usage limits, entitlement checks, or security measures.
        </li>
        <li>Access the Service through automated means (bots, scripts) except as we explicitly permit.</li>
        <li>Reverse-engineer, resell, or sublicense the Service without our written permission.</li>
      </ul>

      <h2>5. Payments</h2>
      <p>
        Credit pack purchases are processed by Razorpay. By purchasing, you authorize us to charge the displayed
        amount to your chosen payment method. Prices are in Indian Rupees (INR) unless stated otherwise.
      </p>

      <h2>6. Disclaimers and limitation of liability</h2>
      <p>
        The Service is provided &ldquo;as is&rdquo; without warranties of any kind. To the maximum extent permitted by
        law, Chirag Digital Pvt Ltd is not liable for any indirect, incidental, or consequential damages arising from
        your use of the Service, including reliance on AI-generated coaching or scoring.
      </p>

      <h2>7. Termination</h2>
      <p>
        We may suspend or terminate your account if you violate these Terms. You may stop using the Service and
        request account deletion at any time by contacting us.
      </p>

      <h2>8. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the Service after a change means you accept the
        updated Terms.
      </p>

      <h2>9. Governing law</h2>
      <p>These Terms are governed by the laws of India.</p>

      <h2>10. Contact</h2>
      <p>
        Questions about these Terms? Email{" "}
        <a href="mailto:hello@bettercallz.com" className="underline underline-offset-4">
          hello@bettercallz.com
        </a>
        .
      </p>
    </LegalPageLayout>
  );
}
